- scripts/issorb.py
The sun/moon avoidance did not work correctly. Swapping the source and
sun/moon in the separation calculation seems to fix this issue. Not sure
why...
> Fix sun/moon avoidance in issorb

- scripts/issorb.py
Add RA/DEC flags to the command line interface of issorb to
override the lookup function. This allows the tool to work for new
sources.
> Add manual RA/DEC to issorb

- scripts/photon_toa.py
Will write barycentric TOAs.  Some issues
-- writes "barycenter" for observatory, needs to be changed to "@" for tempo2 (can fix postprocess, or decide what we want to do)
-- writes to stdout right now, so I grep for what I want to make a TOA file after running something like
for dir in `ls -d *_pipe`; do python photon_toa.py dir/cleanfilt.ev blah blah blah >> output; done
grep nicer output | grep barycenter > test.toas
one option would be to add an interface for specifying a directory and having it do this and make a nice output TOA file.
> Initial implementation of TOA write.

- scripts/ni_data_download.py
- scripts/nicerql.py
- scripts/psrpipe.py
Based on the script by P. Bult:
- I removed the multiprocessing capabilities (the gain in speed was minimal, and it was causing some issues with attempts to decrypt before the untar was finished, or attempts to unzip before the decryption was finished, etc...)
- I also made the whole script fully automatic: user must enter username, password and decryption key (instead of interactive entry)
- I added several checks throughout the code, etc...
(I also remove pythonw in the shebang for nicerql.py and psrpipe.py -- I should not have commited those changes last time - sorry)
> NICER data downloader

- nicer/eng_plots.py
- nicer/plotutils.py
- scripts/nicerql.py
- scripts/psrpipe.py
To plot the spectra of all detectors (on a single figures) and plot the lightcurve of all detectors (on a single figures). For this, I did the following:
- modified the behaviour of plot_energy_spec() and plot_light_curve() with an option (plot_pos) set to None by default, so it will not change the behaviour of all the other calls to these functions.
- added plot_all_spectra() and plot_all_lc() in eng_plots.py, which call plot_energy_spec() and plot_light_curve() with different values for plot_pos.
- added the call to plot_all_spectra() and plot_all_lc()  in nicerql.py
> New plot options

- scripts/cr_cut.py
- scripts/merge.py
- scripts/psrpipe.py
- Merging function is now external to psrpipe (in merge.py), but can still be called from psrpipe.py
- New --crcut option in psrpipe.py to perform count rate cut while merging the event files. NOTE: The count rate cut are not performed for each individual ObsIDs.
> Various improvements to psrpipe

- scripts/nioptcuts.py
- shows H-test significance in sigma.
- plot of H-test grid
>  Update to nioptcuts.py

- scripts/ni_Htest_sortgti.py
I haven't tested it... let me know if it bugs out and I'll fix.
> Add option to use Z^2 test.

- scripts/ni_Htest_sortgti.py
final exposure time was in seconds, but the output said "ksec"
> small bug fix in ni_Htest_sortgti.py

- scripts/ni_Htest_sortgti.py
> Fix energy range printout, and OBO error on emin range.

- scripts/ni_Htest_sortgti.py
Add --minbw and --minexp arguments to enable exclusion of small energy windows and small exposures from the H/Z optimization search.
> New feature to exclude small data selections.

- scripts/ni_Htest_sortgti.py
Add some new options to fine tune searching; incorporate changes from Sebastien for GTI output; fix a bug where TIMEZERO was not being applied to GTI.
> A number of new options and a fix for time offsets.

- scripts/ni_Htest_sortgti.py
Fix a couple of bugs:
(1) apply TIMEZERO regardless of CLOCKAPP (my mistake)
(2) fix OBO bug in GTI selection
> Fix error in applying TIMEZERO, also OBO error elsewhere.

- scripts/ni_Htest_sortgti.py
As title says --
(1) Start encapsulating data and cuts better, to make it easier to extend/check code in future.  (Still more to be done here.)
(2) Improve H/Z^2 test implementation speed, it's about 10x faster now.  This doesn't address the O(time^2) complexity, but it makes searches of ~1Ms datasets feasible now.
There are small differences (<1%) between identical inputs between this version and the previous.
> Some refactoring and performance improvements.

- nicer/fillgaps.py
This update adds a linear slope to the fill points so that, for many cases, there is no longer an abrupt "sawtooth" in the data where filled gaps begin and end. There are still some cases where, if one or two of the endpoints are unusually high/low compared to the surrounding data, the sawtooth may still appear.
> Implemented linear slope / 2 end-pt matching

- nicer/sigmaz.py
Updated nicer/sigmaz.py for better handling of cases where polynomial fits turn out pathological for various reasons.
> Sigma-z: improved handling of pathological cases.

- nicer/fillgaps.py
Impute 1-pt gaps before full algorithm with average of either side pt.
> fillgaps Modification

- nicer/fillgaps.py
The fillgaps script now accounts for outliers within the slope calculation for gap imputation and skips over points that are greater than 5*MAD (median absolute deviation). The script also now takes a csv file as an input (in the format MJD, residual) and outputs a csv in the same format as well as two stacked graphs showing the data before and after imputation. The script can now be called by itself from the command line in the form 'python3 fillgaps.py <inputcsv> reflect+invert'.
> Outliers, I/O, and Script called on its own

- nicer/fillgaps.py
Script takes .csv or .txt input, outputs .csv and graph, and can handle fractional x-coordinates (finds the smallest difference in x-coordinates - in our case MJDs) and bins data in these increments, gaps are in the increments without data.
> Fractional X-Coords and File Input

- scripts/psrpipe.py
Using *mkf file in priority, otherwise the *mkf.gz files
> MKF file selection in psrpipe

- scripts/RPP-scorpeon_yml.py
I added another condition for finding the lines in the log file that contain the parameter uncertainties. This was needed for Mike to be able to run RPP-scorpeon_yml.py to completion for PSR J1024-0719. I have tested that it works on other pulsars, i.e. no new bug is being introduced with this change.
> minor fix on line 76
